# ircserv properties

maxclients=10
servername="ft.irc.local"
opername="root"
operpass="12345"
motdfile="etc/ircserv.motd"

# support list

channellen=50
chanlimit=25
keylen=32
kicklen=255
linelen=512
maxtargets=20
modes=4
network="I-KEA"
nicklen=9
topiclen=307
userlen=18
