# server properties

localmax    = 3                         # max clients from the same host
globalmax   = 7                         # max clients unique hosts
servername  = ft.irc.local
serverhost  = ::                        # IPv6 equivalent of 0.0.0.0
# serverport  = 6667
# serverpass                            # empty password (e.g. severpass=)
maxevents   = 8
polltimeout = 5000                      # timeout unit is milliseconds
opername    = ft_irc
operpass    = 0123456789
motdfile    = etc/ircserv.motd
motdlinelen = 80

# irc support list

chanlimit   = 5
channellen  = 32
hostlen     = 64
keylen      = 16
kicklen     = 307
linelen     = 512
maxtargets  = 1
modes       = 2
network     = I-KEA
nicklen     = 30
topiclen    = 390
userlen     = 18
